package com.itikarus.miska.globals

object KeyUtils {
    val PERMISSION_REQUEST_CODE = 10001
    val REQUEST_CODE_SELECT_FILE = 10002
    val REQUEST_CODE_CAMERA = 10003
    val REQUEST_CODE_CAMERA_FROM_CREATION_PAGE = 10004
    val REQUEST_CODE_CREATE_SPACE = 10005
    val REQUEST_CODE_SHOPPING_CART = 10006
    val INTENT_KEY_IMG_PATH = "imagePath"
    val INTENT_KEY_CREATE_SPACE = "project_ID"
    val INTENT_KEY_SEND_PRODUCT_LIST = "SEND_PRODUCT_LIST"

}
